// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dugjetpanwloxcgcgexx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1Z2pldHBhbndsb3hjZ2NnZXh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MDg4NjgsImV4cCI6MjA3NDA4NDg2OH0.ipJqM1rX3oo7Jr3N5MZS85YvQ_jofT7NRRDlgP98EvE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});